//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SpeedUp.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SystemEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SystemEntities object using the connection string found in the 'SystemEntities' section of the application configuration file.
        /// </summary>
        public SystemEntities() : base("name=SystemEntities", "SystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SystemEntities object.
        /// </summary>
        public SystemEntities(string connectionString) : base(connectionString, "SystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SystemEntities object.
        /// </summary>
        public SystemEntities(EntityConnection connection) : base(connection, "SystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mLSID">No Metadata Documentation available.</param>
        /// <param name="debug">No Metadata Documentation available.</param>
        public ObjectResult<spDA_RETSConnectionInfo_sel_Result> spDA_RETSConnectionInfo_sel(global::System.String mLSID, Nullable<global::System.Boolean> debug)
        {
            ObjectParameter mLSIDParameter;
            if (mLSID != null)
            {
                mLSIDParameter = new ObjectParameter("MLSID", mLSID);
            }
            else
            {
                mLSIDParameter = new ObjectParameter("MLSID", typeof(global::System.String));
            }
    
            ObjectParameter debugParameter;
            if (debug.HasValue)
            {
                debugParameter = new ObjectParameter("debug", debug);
            }
            else
            {
                debugParameter = new ObjectParameter("debug", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction<spDA_RETSConnectionInfo_sel_Result>("spDA_RETSConnectionInfo_sel", mLSIDParameter, debugParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tCSModuleID">No Metadata Documentation available.</param>
        /// <param name="debug">No Metadata Documentation available.</param>
        public ObjectResult<spDA_TCSDatasource_sel_Result> spDA_TCSDatasource_sel(global::System.String tCSModuleID, Nullable<global::System.Boolean> debug)
        {
            ObjectParameter tCSModuleIDParameter;
            if (tCSModuleID != null)
            {
                tCSModuleIDParameter = new ObjectParameter("TCSModuleID", tCSModuleID);
            }
            else
            {
                tCSModuleIDParameter = new ObjectParameter("TCSModuleID", typeof(global::System.String));
            }
    
            ObjectParameter debugParameter;
            if (debug.HasValue)
            {
                debugParameter = new ObjectParameter("Debug", debug);
            }
            else
            {
                debugParameter = new ObjectParameter("Debug", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction<spDA_TCSDatasource_sel_Result>("spDA_TCSDatasource_sel", tCSModuleIDParameter, debugParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iD">No Metadata Documentation available.</param>
        /// <param name="pROTOCOL">No Metadata Documentation available.</param>
        /// <param name="fILEFORMAT">No Metadata Documentation available.</param>
        public ObjectResult<spDA_GetDataSourceConfigBasic_Result> spDA_GetDataSourceConfigBasic(global::System.String iD, global::System.String pROTOCOL, global::System.String fILEFORMAT)
        {
            ObjectParameter iDParameter;
            if (iD != null)
            {
                iDParameter = new ObjectParameter("ID", iD);
            }
            else
            {
                iDParameter = new ObjectParameter("ID", typeof(global::System.String));
            }
    
            ObjectParameter pROTOCOLParameter;
            if (pROTOCOL != null)
            {
                pROTOCOLParameter = new ObjectParameter("PROTOCOL", pROTOCOL);
            }
            else
            {
                pROTOCOLParameter = new ObjectParameter("PROTOCOL", typeof(global::System.String));
            }
    
            ObjectParameter fILEFORMATParameter;
            if (fILEFORMAT != null)
            {
                fILEFORMATParameter = new ObjectParameter("FILEFORMAT", fILEFORMAT);
            }
            else
            {
                fILEFORMATParameter = new ObjectParameter("FILEFORMAT", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spDA_GetDataSourceConfigBasic_Result>("spDA_GetDataSourceConfigBasic", iDParameter, pROTOCOLParameter, fILEFORMATParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<spDA_RETSLoginInfo_sel_Result> spDA_RETSLoginInfo_sel()
        {
            return base.ExecuteFunction<spDA_RETSLoginInfo_sel_Result>("spDA_RETSLoginInfo_sel");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<spDA_RETSListingConfig_sel_Result> spDA_RETSListingConfig_sel()
        {
            return base.ExecuteFunction<spDA_RETSListingConfig_sel_Result>("spDA_RETSListingConfig_sel");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<spDA_RETSRosterConfig_sel_Result> spDA_RETSRosterConfig_sel()
        {
            return base.ExecuteFunction<spDA_RETSRosterConfig_sel_Result>("spDA_RETSRosterConfig_sel");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="dSID">No Metadata Documentation available.</param>
        public ObjectResult<spDA_GetDataSourceID> spDA_GetDataSourceID(global::System.String dSID)
        {
            ObjectParameter dSIDParameter;
            if (dSID != null)
            {
                dSIDParameter = new ObjectParameter("DSID", dSID);
            }
            else
            {
                dSIDParameter = new ObjectParameter("DSID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spDA_GetDataSourceID>("spDA_GetDataSourceID", dSIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<spDA_SoldToActiveDataSource_sel_Result> spDA_SoldToActiveDataSource_sel()
        {
            return base.ExecuteFunction<spDA_SoldToActiveDataSource_sel_Result>("spDA_SoldToActiveDataSource_sel");
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_GetDataSourceConfigBasic_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_GetDataSourceConfigBasic_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_GetDataSourceConfigBasic_Result object.
        /// </summary>
        /// <param name="aggregationSubType">Initial value of the AggregationSubType property.</param>
        /// <param name="aggregationType">Initial value of the AggregationType property.</param>
        /// <param name="dATASOURCECONFIGID">Initial value of the DATASOURCECONFIGID property.</param>
        public static spDA_GetDataSourceConfigBasic_Result CreatespDA_GetDataSourceConfigBasic_Result(global::System.String aggregationSubType, global::System.String aggregationType, global::System.Int32 dATASOURCECONFIGID)
        {
            spDA_GetDataSourceConfigBasic_Result spDA_GetDataSourceConfigBasic_Result = new spDA_GetDataSourceConfigBasic_Result();
            spDA_GetDataSourceConfigBasic_Result.AggregationSubType = aggregationSubType;
            spDA_GetDataSourceConfigBasic_Result.AggregationType = aggregationType;
            spDA_GetDataSourceConfigBasic_Result.DATASOURCECONFIGID = dATASOURCECONFIGID;
            return spDA_GetDataSourceConfigBasic_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AggregationSubType
        {
            get
            {
                return _AggregationSubType;
            }
            set
            {
                OnAggregationSubTypeChanging(value);
                ReportPropertyChanging("AggregationSubType");
                _AggregationSubType = StructuralObject.SetValidValue(value, false, "AggregationSubType");
                ReportPropertyChanged("AggregationSubType");
                OnAggregationSubTypeChanged();
            }
        }
        private global::System.String _AggregationSubType;
        partial void OnAggregationSubTypeChanging(global::System.String value);
        partial void OnAggregationSubTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AggregationType
        {
            get
            {
                return _AggregationType;
            }
            set
            {
                OnAggregationTypeChanging(value);
                ReportPropertyChanging("AggregationType");
                _AggregationType = StructuralObject.SetValidValue(value, false, "AggregationType");
                ReportPropertyChanged("AggregationType");
                OnAggregationTypeChanged();
            }
        }
        private global::System.String _AggregationType;
        partial void OnAggregationTypeChanging(global::System.String value);
        partial void OnAggregationTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProtocolInfo
        {
            get
            {
                return _ProtocolInfo;
            }
            set
            {
                OnProtocolInfoChanging(value);
                ReportPropertyChanging("ProtocolInfo");
                _ProtocolInfo = StructuralObject.SetValidValue(value, true, "ProtocolInfo");
                ReportPropertyChanged("ProtocolInfo");
                OnProtocolInfoChanged();
            }
        }
        private global::System.String _ProtocolInfo;
        partial void OnProtocolInfoChanging(global::System.String value);
        partial void OnProtocolInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileFormatInfo
        {
            get
            {
                return _FileFormatInfo;
            }
            set
            {
                OnFileFormatInfoChanging(value);
                ReportPropertyChanging("FileFormatInfo");
                _FileFormatInfo = StructuralObject.SetValidValue(value, true, "FileFormatInfo");
                ReportPropertyChanged("FileFormatInfo");
                OnFileFormatInfoChanged();
            }
        }
        private global::System.String _FileFormatInfo;
        partial void OnFileFormatInfoChanging(global::System.String value);
        partial void OnFileFormatInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DATASOURCECONFIGID
        {
            get
            {
                return _DATASOURCECONFIGID;
            }
            set
            {
                OnDATASOURCECONFIGIDChanging(value);
                ReportPropertyChanging("DATASOURCECONFIGID");
                _DATASOURCECONFIGID = StructuralObject.SetValidValue(value, "DATASOURCECONFIGID");
                ReportPropertyChanged("DATASOURCECONFIGID");
                OnDATASOURCECONFIGIDChanged();
            }
        }
        private global::System.Int32 _DATASOURCECONFIGID;
        partial void OnDATASOURCECONFIGIDChanging(global::System.Int32 value);
        partial void OnDATASOURCECONFIGIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_GetDataSourceID")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_GetDataSourceID : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_GetDataSourceID object.
        /// </summary>
        /// <param name="dATASOURCEID">Initial value of the DATASOURCEID property.</param>
        public static spDA_GetDataSourceID CreatespDA_GetDataSourceID(global::System.Int32 dATASOURCEID)
        {
            spDA_GetDataSourceID spDA_GetDataSourceID = new spDA_GetDataSourceID();
            spDA_GetDataSourceID.DATASOURCEID = dATASOURCEID;
            return spDA_GetDataSourceID;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DATASOURCEID
        {
            get
            {
                return _DATASOURCEID;
            }
            set
            {
                OnDATASOURCEIDChanging(value);
                ReportPropertyChanging("DATASOURCEID");
                _DATASOURCEID = StructuralObject.SetValidValue(value, "DATASOURCEID");
                ReportPropertyChanged("DATASOURCEID");
                OnDATASOURCEIDChanged();
            }
        }
        private global::System.Int32 _DATASOURCEID;
        partial void OnDATASOURCEIDChanging(global::System.Int32 value);
        partial void OnDATASOURCEIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_RETSConnectionInfo_sel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_RETSConnectionInfo_sel_Result : ComplexObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETSLoginURL
        {
            get
            {
                return _RETSLoginURL;
            }
            set
            {
                OnRETSLoginURLChanging(value);
                ReportPropertyChanging("RETSLoginURL");
                _RETSLoginURL = StructuralObject.SetValidValue(value, true, "RETSLoginURL");
                ReportPropertyChanged("RETSLoginURL");
                OnRETSLoginURLChanged();
            }
        }
        private global::System.String _RETSLoginURL;
        partial void OnRETSLoginURLChanging(global::System.String value);
        partial void OnRETSLoginURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETSUserName
        {
            get
            {
                return _RETSUserName;
            }
            set
            {
                OnRETSUserNameChanging(value);
                ReportPropertyChanging("RETSUserName");
                _RETSUserName = StructuralObject.SetValidValue(value, true, "RETSUserName");
                ReportPropertyChanged("RETSUserName");
                OnRETSUserNameChanged();
            }
        }
        private global::System.String _RETSUserName;
        partial void OnRETSUserNameChanging(global::System.String value);
        partial void OnRETSUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETSPassword
        {
            get
            {
                return _RETSPassword;
            }
            set
            {
                OnRETSPasswordChanging(value);
                ReportPropertyChanging("RETSPassword");
                _RETSPassword = StructuralObject.SetValidValue(value, true, "RETSPassword");
                ReportPropertyChanged("RETSPassword");
                OnRETSPasswordChanged();
            }
        }
        private global::System.String _RETSPassword;
        partial void OnRETSPasswordChanging(global::System.String value);
        partial void OnRETSPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETSUserAgent
        {
            get
            {
                return _RETSUserAgent;
            }
            set
            {
                OnRETSUserAgentChanging(value);
                ReportPropertyChanging("RETSUserAgent");
                _RETSUserAgent = StructuralObject.SetValidValue(value, true, "RETSUserAgent");
                ReportPropertyChanged("RETSUserAgent");
                OnRETSUserAgentChanged();
            }
        }
        private global::System.String _RETSUserAgent;
        partial void OnRETSUserAgentChanging(global::System.String value);
        partial void OnRETSUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETSUserAgentPassword
        {
            get
            {
                return _RETSUserAgentPassword;
            }
            set
            {
                OnRETSUserAgentPasswordChanging(value);
                ReportPropertyChanging("RETSUserAgentPassword");
                _RETSUserAgentPassword = StructuralObject.SetValidValue(value, true, "RETSUserAgentPassword");
                ReportPropertyChanged("RETSUserAgentPassword");
                OnRETSUserAgentPasswordChanged();
            }
        }
        private global::System.String _RETSUserAgentPassword;
        partial void OnRETSUserAgentPasswordChanging(global::System.String value);
        partial void OnRETSUserAgentPasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_RETSListingConfig_sel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_RETSListingConfig_sel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_RETSListingConfig_sel_Result object.
        /// </summary>
        /// <param name="resource_type">Initial value of the resource_type property.</param>
        public static spDA_RETSListingConfig_sel_Result CreatespDA_RETSListingConfig_sel_Result(global::System.String resource_type)
        {
            spDA_RETSListingConfig_sel_Result spDA_RETSListingConfig_sel_Result = new spDA_RETSListingConfig_sel_Result();
            spDA_RETSListingConfig_sel_Result.resource_type = resource_type;
            return spDA_RETSListingConfig_sel_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mls_name
        {
            get
            {
                return _mls_name;
            }
            set
            {
                Onmls_nameChanging(value);
                ReportPropertyChanging("mls_name");
                _mls_name = StructuralObject.SetValidValue(value, true, "mls_name");
                ReportPropertyChanged("mls_name");
                Onmls_nameChanged();
            }
        }
        private global::System.String _mls_name;
        partial void Onmls_nameChanging(global::System.String value);
        partial void Onmls_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data_source_id
        {
            get
            {
                return _data_source_id;
            }
            set
            {
                Ondata_source_idChanging(value);
                ReportPropertyChanging("data_source_id");
                _data_source_id = StructuralObject.SetValidValue(value, true, "data_source_id");
                ReportPropertyChanged("data_source_id");
                Ondata_source_idChanged();
            }
        }
        private global::System.String _data_source_id;
        partial void Ondata_source_idChanging(global::System.String value);
        partial void Ondata_source_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String resource_type
        {
            get
            {
                return _resource_type;
            }
            set
            {
                Onresource_typeChanging(value);
                ReportPropertyChanging("resource_type");
                _resource_type = StructuralObject.SetValidValue(value, false, "resource_type");
                ReportPropertyChanged("resource_type");
                Onresource_typeChanged();
            }
        }
        private global::System.String _resource_type;
        partial void Onresource_typeChanging(global::System.String value);
        partial void Onresource_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resource
        {
            get
            {
                return _resource;
            }
            set
            {
                OnresourceChanging(value);
                ReportPropertyChanging("resource");
                _resource = StructuralObject.SetValidValue(value, true, "resource");
                ReportPropertyChanged("resource");
                OnresourceChanged();
            }
        }
        private global::System.String _resource;
        partial void OnresourceChanging(global::System.String value);
        partial void OnresourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value, true, "class");
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.String _class;
        partial void OnclassChanging(global::System.String value);
        partial void OnclassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_limit
        {
            get
            {
                return _search_limit;
            }
            set
            {
                Onsearch_limitChanging(value);
                ReportPropertyChanging("search_limit");
                _search_limit = StructuralObject.SetValidValue(value, true, "search_limit");
                ReportPropertyChanged("search_limit");
                Onsearch_limitChanged();
            }
        }
        private global::System.String _search_limit;
        partial void Onsearch_limitChanging(global::System.String value);
        partial void Onsearch_limitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_format
        {
            get
            {
                return _search_format;
            }
            set
            {
                Onsearch_formatChanging(value);
                ReportPropertyChanging("search_format");
                _search_format = StructuralObject.SetValidValue(value, true, "search_format");
                ReportPropertyChanged("search_format");
                Onsearch_formatChanged();
            }
        }
        private global::System.String _search_format;
        partial void Onsearch_formatChanging(global::System.String value);
        partial void Onsearch_formatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> count_records_active
        {
            get
            {
                return _count_records_active;
            }
            set
            {
                Oncount_records_activeChanging(value);
                ReportPropertyChanging("count_records_active");
                _count_records_active = StructuralObject.SetValidValue(value, "count_records_active");
                ReportPropertyChanged("count_records_active");
                Oncount_records_activeChanged();
            }
        }
        private Nullable<global::System.Int32> _count_records_active;
        partial void Oncount_records_activeChanging(Nullable<global::System.Int32> value);
        partial void Oncount_records_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String count_records_sold
        {
            get
            {
                return _count_records_sold;
            }
            set
            {
                Oncount_records_soldChanging(value);
                ReportPropertyChanging("count_records_sold");
                _count_records_sold = StructuralObject.SetValidValue(value, true, "count_records_sold");
                ReportPropertyChanged("count_records_sold");
                Oncount_records_soldChanged();
            }
        }
        private global::System.String _count_records_sold;
        partial void Oncount_records_soldChanging(global::System.String value);
        partial void Oncount_records_soldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String count_records_offmarket
        {
            get
            {
                return _count_records_offmarket;
            }
            set
            {
                Oncount_records_offmarketChanging(value);
                ReportPropertyChanging("count_records_offmarket");
                _count_records_offmarket = StructuralObject.SetValidValue(value, true, "count_records_offmarket");
                ReportPropertyChanged("count_records_offmarket");
                Oncount_records_offmarketChanged();
            }
        }
        private global::System.String _count_records_offmarket;
        partial void Oncount_records_offmarketChanging(global::System.String value);
        partial void Oncount_records_offmarketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String last_modified_date_field
        {
            get
            {
                return _last_modified_date_field;
            }
            set
            {
                Onlast_modified_date_fieldChanging(value);
                ReportPropertyChanging("last_modified_date_field");
                _last_modified_date_field = StructuralObject.SetValidValue(value, true, "last_modified_date_field");
                ReportPropertyChanged("last_modified_date_field");
                Onlast_modified_date_fieldChanged();
            }
        }
        private global::System.String _last_modified_date_field;
        partial void Onlast_modified_date_fieldChanging(global::System.String value);
        partial void Onlast_modified_date_fieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String key_field
        {
            get
            {
                return _key_field;
            }
            set
            {
                Onkey_fieldChanging(value);
                ReportPropertyChanging("key_field");
                _key_field = StructuralObject.SetValidValue(value, true, "key_field");
                ReportPropertyChanged("key_field");
                Onkey_fieldChanged();
            }
        }
        private global::System.String _key_field;
        partial void Onkey_fieldChanging(global::System.String value);
        partial void Onkey_fieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sold_date_field
        {
            get
            {
                return _sold_date_field;
            }
            set
            {
                Onsold_date_fieldChanging(value);
                ReportPropertyChanging("sold_date_field");
                _sold_date_field = StructuralObject.SetValidValue(value, true, "sold_date_field");
                ReportPropertyChanged("sold_date_field");
                Onsold_date_fieldChanged();
            }
        }
        private global::System.String _sold_date_field;
        partial void Onsold_date_fieldChanging(global::System.String value);
        partial void Onsold_date_fieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_active_dqml_query
        {
            get
            {
                return _status_active_dqml_query;
            }
            set
            {
                Onstatus_active_dqml_queryChanging(value);
                ReportPropertyChanging("status_active_dqml_query");
                _status_active_dqml_query = StructuralObject.SetValidValue(value, true, "status_active_dqml_query");
                ReportPropertyChanged("status_active_dqml_query");
                Onstatus_active_dqml_queryChanged();
            }
        }
        private global::System.String _status_active_dqml_query;
        partial void Onstatus_active_dqml_queryChanging(global::System.String value);
        partial void Onstatus_active_dqml_queryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_sold_dqml_query
        {
            get
            {
                return _status_sold_dqml_query;
            }
            set
            {
                Onstatus_sold_dqml_queryChanging(value);
                ReportPropertyChanging("status_sold_dqml_query");
                _status_sold_dqml_query = StructuralObject.SetValidValue(value, true, "status_sold_dqml_query");
                ReportPropertyChanged("status_sold_dqml_query");
                Onstatus_sold_dqml_queryChanged();
            }
        }
        private global::System.String _status_sold_dqml_query;
        partial void Onstatus_sold_dqml_queryChanging(global::System.String value);
        partial void Onstatus_sold_dqml_queryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_offmarket_dqml_query
        {
            get
            {
                return _status_offmarket_dqml_query;
            }
            set
            {
                Onstatus_offmarket_dqml_queryChanging(value);
                ReportPropertyChanging("status_offmarket_dqml_query");
                _status_offmarket_dqml_query = StructuralObject.SetValidValue(value, true, "status_offmarket_dqml_query");
                ReportPropertyChanged("status_offmarket_dqml_query");
                Onstatus_offmarket_dqml_queryChanged();
            }
        }
        private global::System.String _status_offmarket_dqml_query;
        partial void Onstatus_offmarket_dqml_queryChanging(global::System.String value);
        partial void Onstatus_offmarket_dqml_queryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_type
        {
            get
            {
                return _photo_type;
            }
            set
            {
                Onphoto_typeChanging(value);
                ReportPropertyChanging("photo_type");
                _photo_type = StructuralObject.SetValidValue(value, true, "photo_type");
                ReportPropertyChanged("photo_type");
                Onphoto_typeChanged();
            }
        }
        private global::System.String _photo_type;
        partial void Onphoto_typeChanging(global::System.String value);
        partial void Onphoto_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_last_modified_field
        {
            get
            {
                return _photo_last_modified_field;
            }
            set
            {
                Onphoto_last_modified_fieldChanging(value);
                ReportPropertyChanging("photo_last_modified_field");
                _photo_last_modified_field = StructuralObject.SetValidValue(value, true, "photo_last_modified_field");
                ReportPropertyChanged("photo_last_modified_field");
                Onphoto_last_modified_fieldChanged();
            }
        }
        private global::System.String _photo_last_modified_field;
        partial void Onphoto_last_modified_fieldChanging(global::System.String value);
        partial void Onphoto_last_modified_fieldChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_RETSLoginInfo_sel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_RETSLoginInfo_sel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_RETSLoginInfo_sel_Result object.
        /// </summary>
        /// <param name="mls_name">Initial value of the mls_name property.</param>
        /// <param name="data_source_id">Initial value of the data_source_id property.</param>
        /// <param name="login_type">Initial value of the login_type property.</param>
        public static spDA_RETSLoginInfo_sel_Result CreatespDA_RETSLoginInfo_sel_Result(global::System.String mls_name, global::System.String data_source_id, global::System.String login_type)
        {
            spDA_RETSLoginInfo_sel_Result spDA_RETSLoginInfo_sel_Result = new spDA_RETSLoginInfo_sel_Result();
            spDA_RETSLoginInfo_sel_Result.mls_name = mls_name;
            spDA_RETSLoginInfo_sel_Result.data_source_id = data_source_id;
            spDA_RETSLoginInfo_sel_Result.login_type = login_type;
            return spDA_RETSLoginInfo_sel_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mls_name
        {
            get
            {
                return _mls_name;
            }
            set
            {
                Onmls_nameChanging(value);
                ReportPropertyChanging("mls_name");
                _mls_name = StructuralObject.SetValidValue(value, false, "mls_name");
                ReportPropertyChanged("mls_name");
                Onmls_nameChanged();
            }
        }
        private global::System.String _mls_name;
        partial void Onmls_nameChanging(global::System.String value);
        partial void Onmls_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String data_source_id
        {
            get
            {
                return _data_source_id;
            }
            set
            {
                Ondata_source_idChanging(value);
                ReportPropertyChanging("data_source_id");
                _data_source_id = StructuralObject.SetValidValue(value, false, "data_source_id");
                ReportPropertyChanged("data_source_id");
                Ondata_source_idChanged();
            }
        }
        private global::System.String _data_source_id;
        partial void Ondata_source_idChanging(global::System.String value);
        partial void Ondata_source_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login_type
        {
            get
            {
                return _login_type;
            }
            set
            {
                Onlogin_typeChanging(value);
                ReportPropertyChanging("login_type");
                _login_type = StructuralObject.SetValidValue(value, false, "login_type");
                ReportPropertyChanged("login_type");
                Onlogin_typeChanged();
            }
        }
        private global::System.String _login_type;
        partial void Onlogin_typeChanging(global::System.String value);
        partial void Onlogin_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rets_url
        {
            get
            {
                return _rets_url;
            }
            set
            {
                Onrets_urlChanging(value);
                ReportPropertyChanging("rets_url");
                _rets_url = StructuralObject.SetValidValue(value, true, "rets_url");
                ReportPropertyChanged("rets_url");
                Onrets_urlChanged();
            }
        }
        private global::System.String _rets_url;
        partial void Onrets_urlChanging(global::System.String value);
        partial void Onrets_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, true, "user_name");
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_agent
        {
            get
            {
                return _user_agent;
            }
            set
            {
                Onuser_agentChanging(value);
                ReportPropertyChanging("user_agent");
                _user_agent = StructuralObject.SetValidValue(value, true, "user_agent");
                ReportPropertyChanged("user_agent");
                Onuser_agentChanged();
            }
        }
        private global::System.String _user_agent;
        partial void Onuser_agentChanging(global::System.String value);
        partial void Onuser_agentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_agent_password
        {
            get
            {
                return _user_agent_password;
            }
            set
            {
                Onuser_agent_passwordChanging(value);
                ReportPropertyChanging("user_agent_password");
                _user_agent_password = StructuralObject.SetValidValue(value, true, "user_agent_password");
                ReportPropertyChanged("user_agent_password");
                Onuser_agent_passwordChanged();
            }
        }
        private global::System.String _user_agent_password;
        partial void Onuser_agent_passwordChanging(global::System.String value);
        partial void Onuser_agent_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rets_version
        {
            get
            {
                return _rets_version;
            }
            set
            {
                Onrets_versionChanging(value);
                ReportPropertyChanging("rets_version");
                _rets_version = StructuralObject.SetValidValue(value, true, "rets_version");
                ReportPropertyChanged("rets_version");
                Onrets_versionChanged();
            }
        }
        private global::System.String _rets_version;
        partial void Onrets_versionChanging(global::System.String value);
        partial void Onrets_versionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String http_version
        {
            get
            {
                return _http_version;
            }
            set
            {
                Onhttp_versionChanging(value);
                ReportPropertyChanging("http_version");
                _http_version = StructuralObject.SetValidValue(value, true, "http_version");
                ReportPropertyChanged("http_version");
                Onhttp_versionChanged();
            }
        }
        private global::System.String _http_version;
        partial void Onhttp_versionChanging(global::System.String value);
        partial void Onhttp_versionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String http_method
        {
            get
            {
                return _http_method;
            }
            set
            {
                Onhttp_methodChanging(value);
                ReportPropertyChanging("http_method");
                _http_method = StructuralObject.SetValidValue(value, true, "http_method");
                ReportPropertyChanged("http_method");
                Onhttp_methodChanged();
            }
        }
        private global::System.String _http_method;
        partial void Onhttp_methodChanging(global::System.String value);
        partial void Onhttp_methodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auth_type
        {
            get
            {
                return _auth_type;
            }
            set
            {
                Onauth_typeChanging(value);
                ReportPropertyChanging("auth_type");
                _auth_type = StructuralObject.SetValidValue(value, true, "auth_type");
                ReportPropertyChanged("auth_type");
                Onauth_typeChanged();
            }
        }
        private global::System.String _auth_type;
        partial void Onauth_typeChanging(global::System.String value);
        partial void Onauth_typeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_RETSRosterConfig_sel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_RETSRosterConfig_sel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_RETSRosterConfig_sel_Result object.
        /// </summary>
        /// <param name="resource_type">Initial value of the resource_type property.</param>
        public static spDA_RETSRosterConfig_sel_Result CreatespDA_RETSRosterConfig_sel_Result(global::System.String resource_type)
        {
            spDA_RETSRosterConfig_sel_Result spDA_RETSRosterConfig_sel_Result = new spDA_RETSRosterConfig_sel_Result();
            spDA_RETSRosterConfig_sel_Result.resource_type = resource_type;
            return spDA_RETSRosterConfig_sel_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mls_name
        {
            get
            {
                return _mls_name;
            }
            set
            {
                Onmls_nameChanging(value);
                ReportPropertyChanging("mls_name");
                _mls_name = StructuralObject.SetValidValue(value, true, "mls_name");
                ReportPropertyChanged("mls_name");
                Onmls_nameChanged();
            }
        }
        private global::System.String _mls_name;
        partial void Onmls_nameChanging(global::System.String value);
        partial void Onmls_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data_source_id
        {
            get
            {
                return _data_source_id;
            }
            set
            {
                Ondata_source_idChanging(value);
                ReportPropertyChanging("data_source_id");
                _data_source_id = StructuralObject.SetValidValue(value, true, "data_source_id");
                ReportPropertyChanged("data_source_id");
                Ondata_source_idChanged();
            }
        }
        private global::System.String _data_source_id;
        partial void Ondata_source_idChanging(global::System.String value);
        partial void Ondata_source_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String resource_type
        {
            get
            {
                return _resource_type;
            }
            set
            {
                Onresource_typeChanging(value);
                ReportPropertyChanging("resource_type");
                _resource_type = StructuralObject.SetValidValue(value, false, "resource_type");
                ReportPropertyChanged("resource_type");
                Onresource_typeChanged();
            }
        }
        private global::System.String _resource_type;
        partial void Onresource_typeChanging(global::System.String value);
        partial void Onresource_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resource
        {
            get
            {
                return _resource;
            }
            set
            {
                OnresourceChanging(value);
                ReportPropertyChanging("resource");
                _resource = StructuralObject.SetValidValue(value, true, "resource");
                ReportPropertyChanged("resource");
                OnresourceChanged();
            }
        }
        private global::System.String _resource;
        partial void OnresourceChanging(global::System.String value);
        partial void OnresourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value, true, "class");
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.String _class;
        partial void OnclassChanging(global::System.String value);
        partial void OnclassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_limit
        {
            get
            {
                return _search_limit;
            }
            set
            {
                Onsearch_limitChanging(value);
                ReportPropertyChanging("search_limit");
                _search_limit = StructuralObject.SetValidValue(value, true, "search_limit");
                ReportPropertyChanged("search_limit");
                Onsearch_limitChanged();
            }
        }
        private global::System.String _search_limit;
        partial void Onsearch_limitChanging(global::System.String value);
        partial void Onsearch_limitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_format
        {
            get
            {
                return _search_format;
            }
            set
            {
                Onsearch_formatChanging(value);
                ReportPropertyChanging("search_format");
                _search_format = StructuralObject.SetValidValue(value, true, "search_format");
                ReportPropertyChanged("search_format");
                Onsearch_formatChanged();
            }
        }
        private global::System.String _search_format;
        partial void Onsearch_formatChanging(global::System.String value);
        partial void Onsearch_formatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> count_records_active
        {
            get
            {
                return _count_records_active;
            }
            set
            {
                Oncount_records_activeChanging(value);
                ReportPropertyChanging("count_records_active");
                _count_records_active = StructuralObject.SetValidValue(value, "count_records_active");
                ReportPropertyChanged("count_records_active");
                Oncount_records_activeChanged();
            }
        }
        private Nullable<global::System.Int32> _count_records_active;
        partial void Oncount_records_activeChanging(Nullable<global::System.Int32> value);
        partial void Oncount_records_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String last_modified_date_field
        {
            get
            {
                return _last_modified_date_field;
            }
            set
            {
                Onlast_modified_date_fieldChanging(value);
                ReportPropertyChanging("last_modified_date_field");
                _last_modified_date_field = StructuralObject.SetValidValue(value, true, "last_modified_date_field");
                ReportPropertyChanged("last_modified_date_field");
                Onlast_modified_date_fieldChanged();
            }
        }
        private global::System.String _last_modified_date_field;
        partial void Onlast_modified_date_fieldChanging(global::System.String value);
        partial void Onlast_modified_date_fieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String key_field
        {
            get
            {
                return _key_field;
            }
            set
            {
                Onkey_fieldChanging(value);
                ReportPropertyChanging("key_field");
                _key_field = StructuralObject.SetValidValue(value, true, "key_field");
                ReportPropertyChanged("key_field");
                Onkey_fieldChanged();
            }
        }
        private global::System.String _key_field;
        partial void Onkey_fieldChanging(global::System.String value);
        partial void Onkey_fieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_active_dqml_query
        {
            get
            {
                return _status_active_dqml_query;
            }
            set
            {
                Onstatus_active_dqml_queryChanging(value);
                ReportPropertyChanging("status_active_dqml_query");
                _status_active_dqml_query = StructuralObject.SetValidValue(value, true, "status_active_dqml_query");
                ReportPropertyChanged("status_active_dqml_query");
                Onstatus_active_dqml_queryChanged();
            }
        }
        private global::System.String _status_active_dqml_query;
        partial void Onstatus_active_dqml_queryChanging(global::System.String value);
        partial void Onstatus_active_dqml_queryChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_SoldToActiveDataSource_sel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_SoldToActiveDataSource_sel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_SoldToActiveDataSource_sel_Result object.
        /// </summary>
        /// <param name="sold_data_source_id">Initial value of the sold_data_source_id property.</param>
        /// <param name="sold_mls_name">Initial value of the sold_mls_name property.</param>
        public static spDA_SoldToActiveDataSource_sel_Result CreatespDA_SoldToActiveDataSource_sel_Result(global::System.String sold_data_source_id, global::System.String sold_mls_name)
        {
            spDA_SoldToActiveDataSource_sel_Result spDA_SoldToActiveDataSource_sel_Result = new spDA_SoldToActiveDataSource_sel_Result();
            spDA_SoldToActiveDataSource_sel_Result.sold_data_source_id = sold_data_source_id;
            spDA_SoldToActiveDataSource_sel_Result.sold_mls_name = sold_mls_name;
            return spDA_SoldToActiveDataSource_sel_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sold_data_source_id
        {
            get
            {
                return _sold_data_source_id;
            }
            set
            {
                Onsold_data_source_idChanging(value);
                ReportPropertyChanging("sold_data_source_id");
                _sold_data_source_id = StructuralObject.SetValidValue(value, false, "sold_data_source_id");
                ReportPropertyChanged("sold_data_source_id");
                Onsold_data_source_idChanged();
            }
        }
        private global::System.String _sold_data_source_id;
        partial void Onsold_data_source_idChanging(global::System.String value);
        partial void Onsold_data_source_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sold_mls_name
        {
            get
            {
                return _sold_mls_name;
            }
            set
            {
                Onsold_mls_nameChanging(value);
                ReportPropertyChanging("sold_mls_name");
                _sold_mls_name = StructuralObject.SetValidValue(value, false, "sold_mls_name");
                ReportPropertyChanged("sold_mls_name");
                Onsold_mls_nameChanged();
            }
        }
        private global::System.String _sold_mls_name;
        partial void Onsold_mls_nameChanging(global::System.String value);
        partial void Onsold_mls_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String main_data_source_id
        {
            get
            {
                return _main_data_source_id;
            }
            set
            {
                Onmain_data_source_idChanging(value);
                ReportPropertyChanging("main_data_source_id");
                _main_data_source_id = StructuralObject.SetValidValue(value, true, "main_data_source_id");
                ReportPropertyChanged("main_data_source_id");
                Onmain_data_source_idChanged();
            }
        }
        private global::System.String _main_data_source_id;
        partial void Onmain_data_source_idChanging(global::System.String value);
        partial void Onmain_data_source_idChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SystemModel", Name="spDA_TCSDatasource_sel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spDA_TCSDatasource_sel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spDA_TCSDatasource_sel_Result object.
        /// </summary>
        /// <param name="originalDataSourceID">Initial value of the OriginalDataSourceID property.</param>
        /// <param name="datasourcename">Initial value of the datasourcename property.</param>
        /// <param name="tCSModuleID">Initial value of the TCSModuleID property.</param>
        /// <param name="datasourceid">Initial value of the datasourceid property.</param>
        public static spDA_TCSDatasource_sel_Result CreatespDA_TCSDatasource_sel_Result(global::System.String originalDataSourceID, global::System.String datasourcename, global::System.String tCSModuleID, global::System.Int32 datasourceid)
        {
            spDA_TCSDatasource_sel_Result spDA_TCSDatasource_sel_Result = new spDA_TCSDatasource_sel_Result();
            spDA_TCSDatasource_sel_Result.OriginalDataSourceID = originalDataSourceID;
            spDA_TCSDatasource_sel_Result.datasourcename = datasourcename;
            spDA_TCSDatasource_sel_Result.TCSModuleID = tCSModuleID;
            spDA_TCSDatasource_sel_Result.datasourceid = datasourceid;
            return spDA_TCSDatasource_sel_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OriginalDataSourceID
        {
            get
            {
                return _OriginalDataSourceID;
            }
            set
            {
                OnOriginalDataSourceIDChanging(value);
                ReportPropertyChanging("OriginalDataSourceID");
                _OriginalDataSourceID = StructuralObject.SetValidValue(value, false, "OriginalDataSourceID");
                ReportPropertyChanged("OriginalDataSourceID");
                OnOriginalDataSourceIDChanged();
            }
        }
        private global::System.String _OriginalDataSourceID;
        partial void OnOriginalDataSourceIDChanging(global::System.String value);
        partial void OnOriginalDataSourceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String datasourcename
        {
            get
            {
                return _datasourcename;
            }
            set
            {
                OndatasourcenameChanging(value);
                ReportPropertyChanging("datasourcename");
                _datasourcename = StructuralObject.SetValidValue(value, false, "datasourcename");
                ReportPropertyChanged("datasourcename");
                OndatasourcenameChanged();
            }
        }
        private global::System.String _datasourcename;
        partial void OndatasourcenameChanging(global::System.String value);
        partial void OndatasourcenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TCSModuleID
        {
            get
            {
                return _TCSModuleID;
            }
            set
            {
                OnTCSModuleIDChanging(value);
                ReportPropertyChanging("TCSModuleID");
                _TCSModuleID = StructuralObject.SetValidValue(value, false, "TCSModuleID");
                ReportPropertyChanged("TCSModuleID");
                OnTCSModuleIDChanged();
            }
        }
        private global::System.String _TCSModuleID;
        partial void OnTCSModuleIDChanging(global::System.String value);
        partial void OnTCSModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 datasourceid
        {
            get
            {
                return _datasourceid;
            }
            set
            {
                OndatasourceidChanging(value);
                ReportPropertyChanging("datasourceid");
                _datasourceid = StructuralObject.SetValidValue(value, "datasourceid");
                ReportPropertyChanged("datasourceid");
                OndatasourceidChanged();
            }
        }
        private global::System.Int32 _datasourceid;
        partial void OndatasourceidChanging(global::System.Int32 value);
        partial void OndatasourceidChanged();

        #endregion

    }

    #endregion

}
