//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TCSModelProduction", "FK_LOG_HAS_ERROR", "tcs_request_log", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SpeedUp.Model.tcs_request_log), "tcs_error_log", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SpeedUp.Model.tcs_error_log), true)]
[assembly: EdmRelationshipAttribute("TCSModelProduction", "FK_tcs_indexed_datasources_cma_mls_modules", "cma_mls_modules", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SpeedUp.Model.cma_mls_modules), "tcs_indexed_datasources", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SpeedUp.Model.tcs_indexed_datasources), true)]

#endregion

namespace SpeedUp.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TCSEntitiesProduction : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TCSEntitiesProduction object using the connection string found in the 'TCSEntitiesProduction' section of the application configuration file.
        /// </summary>
        public TCSEntitiesProduction() : base("name=TCSEntitiesProduction", "TCSEntitiesProduction")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TCSEntitiesProduction object.
        /// </summary>
        public TCSEntitiesProduction(string connectionString) : base(connectionString, "TCSEntitiesProduction")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TCSEntitiesProduction object.
        /// </summary>
        public TCSEntitiesProduction(EntityConnection connection) : base(connection, "TCSEntitiesProduction")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tcs_error_log> tcs_error_log
        {
            get
            {
                if ((_tcs_error_log == null))
                {
                    _tcs_error_log = base.CreateObjectSet<tcs_error_log>("tcs_error_log");
                }
                return _tcs_error_log;
            }
        }
        private ObjectSet<tcs_error_log> _tcs_error_log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tcs_request_log> tcs_request_log
        {
            get
            {
                if ((_tcs_request_log == null))
                {
                    _tcs_request_log = base.CreateObjectSet<tcs_request_log>("tcs_request_log");
                }
                return _tcs_request_log;
            }
        }
        private ObjectSet<tcs_request_log> _tcs_request_log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cma_mls_board_connections> cma_mls_board_connections
        {
            get
            {
                if ((_cma_mls_board_connections == null))
                {
                    _cma_mls_board_connections = base.CreateObjectSet<cma_mls_board_connections>("cma_mls_board_connections");
                }
                return _cma_mls_board_connections;
            }
        }
        private ObjectSet<cma_mls_board_connections> _cma_mls_board_connections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cma_mls_boards> cma_mls_boards
        {
            get
            {
                if ((_cma_mls_boards == null))
                {
                    _cma_mls_boards = base.CreateObjectSet<cma_mls_boards>("cma_mls_boards");
                }
                return _cma_mls_boards;
            }
        }
        private ObjectSet<cma_mls_boards> _cma_mls_boards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cma_mls_modules> cma_mls_modules
        {
            get
            {
                if ((_cma_mls_modules == null))
                {
                    _cma_mls_modules = base.CreateObjectSet<cma_mls_modules>("cma_mls_modules");
                }
                return _cma_mls_modules;
            }
        }
        private ObjectSet<cma_mls_modules> _cma_mls_modules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tcs_indexed_datasources> tcs_indexed_datasources
        {
            get
            {
                if ((_tcs_indexed_datasources == null))
                {
                    _tcs_indexed_datasources = base.CreateObjectSet<tcs_indexed_datasources>("tcs_indexed_datasources");
                }
                return _tcs_indexed_datasources;
            }
        }
        private ObjectSet<tcs_indexed_datasources> _tcs_indexed_datasources;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tcs_module_id_to_data_source_id> tcs_module_id_to_data_source_id
        {
            get
            {
                if ((_tcs_module_id_to_data_source_id == null))
                {
                    _tcs_module_id_to_data_source_id = base.CreateObjectSet<tcs_module_id_to_data_source_id>("tcs_module_id_to_data_source_id");
                }
                return _tcs_module_id_to_data_source_id;
            }
        }
        private ObjectSet<tcs_module_id_to_data_source_id> _tcs_module_id_to_data_source_id;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tcs_error_log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotcs_error_log(tcs_error_log tcs_error_log)
        {
            base.AddObject("tcs_error_log", tcs_error_log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tcs_request_log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotcs_request_log(tcs_request_log tcs_request_log)
        {
            base.AddObject("tcs_request_log", tcs_request_log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cma_mls_board_connections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocma_mls_board_connections(cma_mls_board_connections cma_mls_board_connections)
        {
            base.AddObject("cma_mls_board_connections", cma_mls_board_connections);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cma_mls_boards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocma_mls_boards(cma_mls_boards cma_mls_boards)
        {
            base.AddObject("cma_mls_boards", cma_mls_boards);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cma_mls_modules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocma_mls_modules(cma_mls_modules cma_mls_modules)
        {
            base.AddObject("cma_mls_modules", cma_mls_modules);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tcs_indexed_datasources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotcs_indexed_datasources(tcs_indexed_datasources tcs_indexed_datasources)
        {
            base.AddObject("tcs_indexed_datasources", tcs_indexed_datasources);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tcs_module_id_to_data_source_id EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotcs_module_id_to_data_source_id(tcs_module_id_to_data_source_id tcs_module_id_to_data_source_id)
        {
            base.AddObject("tcs_module_id_to_data_source_id", tcs_module_id_to_data_source_id);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="module_id">No Metadata Documentation available.</param>
        public ObjectResult<tcs_GetBoardID_Result> tcs_GetBoardID(Nullable<global::System.Int16> module_id)
        {
            ObjectParameter module_idParameter;
            if (module_id.HasValue)
            {
                module_idParameter = new ObjectParameter("module_id", module_id);
            }
            else
            {
                module_idParameter = new ObjectParameter("module_id", typeof(global::System.Int16));
            }
    
            return base.ExecuteFunction<tcs_GetBoardID_Result>("tcs_GetBoardID", module_idParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="cma_mls_board_connections")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cma_mls_board_connections : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cma_mls_board_connections object.
        /// </summary>
        /// <param name="connection_id">Initial value of the connection_id property.</param>
        /// <param name="definition_file">Initial value of the definition_file property.</param>
        /// <param name="connection_type">Initial value of the connection_type property.</param>
        /// <param name="connection_name">Initial value of the connection_name property.</param>
        /// <param name="version">Initial value of the version property.</param>
        /// <param name="when_checked">Initial value of the when_checked property.</param>
        /// <param name="is_login_required">Initial value of the is_login_required property.</param>
        /// <param name="connection_status_id">Initial value of the connection_status_id property.</param>
        public static cma_mls_board_connections Createcma_mls_board_connections(global::System.Guid connection_id, global::System.String definition_file, global::System.String connection_type, global::System.String connection_name, global::System.String version, global::System.DateTime when_checked, global::System.Int16 is_login_required, global::System.Int16 connection_status_id)
        {
            cma_mls_board_connections cma_mls_board_connections = new cma_mls_board_connections();
            cma_mls_board_connections.connection_id = connection_id;
            cma_mls_board_connections.definition_file = definition_file;
            cma_mls_board_connections.connection_type = connection_type;
            cma_mls_board_connections.connection_name = connection_name;
            cma_mls_board_connections.version = version;
            cma_mls_board_connections.when_checked = when_checked;
            cma_mls_board_connections.is_login_required = is_login_required;
            cma_mls_board_connections.connection_status_id = connection_status_id;
            return cma_mls_board_connections;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> board_id
        {
            get
            {
                return _board_id;
            }
            set
            {
                Onboard_idChanging(value);
                ReportPropertyChanging("board_id");
                _board_id = StructuralObject.SetValidValue(value, "board_id");
                ReportPropertyChanged("board_id");
                Onboard_idChanged();
            }
        }
        private Nullable<global::System.Int16> _board_id;
        partial void Onboard_idChanging(Nullable<global::System.Int16> value);
        partial void Onboard_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid connection_id
        {
            get
            {
                return _connection_id;
            }
            set
            {
                if (_connection_id != value)
                {
                    Onconnection_idChanging(value);
                    ReportPropertyChanging("connection_id");
                    _connection_id = StructuralObject.SetValidValue(value, "connection_id");
                    ReportPropertyChanged("connection_id");
                    Onconnection_idChanged();
                }
            }
        }
        private global::System.Guid _connection_id;
        partial void Onconnection_idChanging(global::System.Guid value);
        partial void Onconnection_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String definition_file
        {
            get
            {
                return _definition_file;
            }
            set
            {
                Ondefinition_fileChanging(value);
                ReportPropertyChanging("definition_file");
                _definition_file = StructuralObject.SetValidValue(value, false, "definition_file");
                ReportPropertyChanged("definition_file");
                Ondefinition_fileChanged();
            }
        }
        private global::System.String _definition_file;
        partial void Ondefinition_fileChanging(global::System.String value);
        partial void Ondefinition_fileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String connection_type
        {
            get
            {
                return _connection_type;
            }
            set
            {
                Onconnection_typeChanging(value);
                ReportPropertyChanging("connection_type");
                _connection_type = StructuralObject.SetValidValue(value, false, "connection_type");
                ReportPropertyChanged("connection_type");
                Onconnection_typeChanged();
            }
        }
        private global::System.String _connection_type;
        partial void Onconnection_typeChanging(global::System.String value);
        partial void Onconnection_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String connection_name
        {
            get
            {
                return _connection_name;
            }
            set
            {
                Onconnection_nameChanging(value);
                ReportPropertyChanging("connection_name");
                _connection_name = StructuralObject.SetValidValue(value, false, "connection_name");
                ReportPropertyChanged("connection_name");
                Onconnection_nameChanged();
            }
        }
        private global::System.String _connection_name;
        partial void Onconnection_nameChanging(global::System.String value);
        partial void Onconnection_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, false, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private global::System.String _version;
        partial void OnversionChanging(global::System.String value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime when_checked
        {
            get
            {
                return _when_checked;
            }
            set
            {
                Onwhen_checkedChanging(value);
                ReportPropertyChanging("when_checked");
                _when_checked = StructuralObject.SetValidValue(value, "when_checked");
                ReportPropertyChanged("when_checked");
                Onwhen_checkedChanged();
            }
        }
        private global::System.DateTime _when_checked;
        partial void Onwhen_checkedChanging(global::System.DateTime value);
        partial void Onwhen_checkedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 is_login_required
        {
            get
            {
                return _is_login_required;
            }
            set
            {
                Onis_login_requiredChanging(value);
                ReportPropertyChanging("is_login_required");
                _is_login_required = StructuralObject.SetValidValue(value, "is_login_required");
                ReportPropertyChanged("is_login_required");
                Onis_login_requiredChanged();
            }
        }
        private global::System.Int16 _is_login_required;
        partial void Onis_login_requiredChanging(global::System.Int16 value);
        partial void Onis_login_requiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 connection_status_id
        {
            get
            {
                return _connection_status_id;
            }
            set
            {
                Onconnection_status_idChanging(value);
                ReportPropertyChanging("connection_status_id");
                _connection_status_id = StructuralObject.SetValidValue(value, "connection_status_id");
                ReportPropertyChanged("connection_status_id");
                Onconnection_status_idChanged();
            }
        }
        private global::System.Int16 _connection_status_id;
        partial void Onconnection_status_idChanging(global::System.Int16 value);
        partial void Onconnection_status_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content_xml
        {
            get
            {
                return _content_xml;
            }
            set
            {
                Oncontent_xmlChanging(value);
                ReportPropertyChanging("content_xml");
                _content_xml = StructuralObject.SetValidValue(value, true, "content_xml");
                ReportPropertyChanged("content_xml");
                Oncontent_xmlChanged();
            }
        }
        private global::System.String _content_xml;
        partial void Oncontent_xmlChanging(global::System.String value);
        partial void Oncontent_xmlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="cma_mls_boards")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cma_mls_boards : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cma_mls_boards object.
        /// </summary>
        /// <param name="language_id">Initial value of the language_id property.</param>
        /// <param name="board_id">Initial value of the board_id property.</param>
        /// <param name="board_name">Initial value of the board_name property.</param>
        /// <param name="vendor_name">Initial value of the vendor_name property.</param>
        /// <param name="state_name">Initial value of the state_name property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="url_location_path">Initial value of the url_location_path property.</param>
        /// <param name="board_status_id">Initial value of the board_status_id property.</param>
        /// <param name="module_id">Initial value of the module_id property.</param>
        public static cma_mls_boards Createcma_mls_boards(global::System.Int16 language_id, global::System.Int16 board_id, global::System.String board_name, global::System.String vendor_name, global::System.String state_name, global::System.String type, global::System.String url_location_path, global::System.Int16 board_status_id, global::System.Int16 module_id)
        {
            cma_mls_boards cma_mls_boards = new cma_mls_boards();
            cma_mls_boards.language_id = language_id;
            cma_mls_boards.board_id = board_id;
            cma_mls_boards.board_name = board_name;
            cma_mls_boards.vendor_name = vendor_name;
            cma_mls_boards.state_name = state_name;
            cma_mls_boards.type = type;
            cma_mls_boards.url_location_path = url_location_path;
            cma_mls_boards.board_status_id = board_status_id;
            cma_mls_boards.module_id = module_id;
            return cma_mls_boards;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 language_id
        {
            get
            {
                return _language_id;
            }
            set
            {
                if (_language_id != value)
                {
                    Onlanguage_idChanging(value);
                    ReportPropertyChanging("language_id");
                    _language_id = StructuralObject.SetValidValue(value, "language_id");
                    ReportPropertyChanged("language_id");
                    Onlanguage_idChanged();
                }
            }
        }
        private global::System.Int16 _language_id;
        partial void Onlanguage_idChanging(global::System.Int16 value);
        partial void Onlanguage_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 board_id
        {
            get
            {
                return _board_id;
            }
            set
            {
                if (_board_id != value)
                {
                    Onboard_idChanging(value);
                    ReportPropertyChanging("board_id");
                    _board_id = StructuralObject.SetValidValue(value, "board_id");
                    ReportPropertyChanged("board_id");
                    Onboard_idChanged();
                }
            }
        }
        private global::System.Int16 _board_id;
        partial void Onboard_idChanging(global::System.Int16 value);
        partial void Onboard_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String board_name
        {
            get
            {
                return _board_name;
            }
            set
            {
                Onboard_nameChanging(value);
                ReportPropertyChanging("board_name");
                _board_name = StructuralObject.SetValidValue(value, false, "board_name");
                ReportPropertyChanged("board_name");
                Onboard_nameChanged();
            }
        }
        private global::System.String _board_name;
        partial void Onboard_nameChanging(global::System.String value);
        partial void Onboard_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vendor_name
        {
            get
            {
                return _vendor_name;
            }
            set
            {
                Onvendor_nameChanging(value);
                ReportPropertyChanging("vendor_name");
                _vendor_name = StructuralObject.SetValidValue(value, false, "vendor_name");
                ReportPropertyChanged("vendor_name");
                Onvendor_nameChanged();
            }
        }
        private global::System.String _vendor_name;
        partial void Onvendor_nameChanging(global::System.String value);
        partial void Onvendor_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String state_name
        {
            get
            {
                return _state_name;
            }
            set
            {
                Onstate_nameChanging(value);
                ReportPropertyChanging("state_name");
                _state_name = StructuralObject.SetValidValue(value, false, "state_name");
                ReportPropertyChanged("state_name");
                Onstate_nameChanged();
            }
        }
        private global::System.String _state_name;
        partial void Onstate_nameChanging(global::System.String value);
        partial void Onstate_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false, "type");
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url_location_path
        {
            get
            {
                return _url_location_path;
            }
            set
            {
                Onurl_location_pathChanging(value);
                ReportPropertyChanging("url_location_path");
                _url_location_path = StructuralObject.SetValidValue(value, false, "url_location_path");
                ReportPropertyChanged("url_location_path");
                Onurl_location_pathChanged();
            }
        }
        private global::System.String _url_location_path;
        partial void Onurl_location_pathChanging(global::System.String value);
        partial void Onurl_location_pathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 board_status_id
        {
            get
            {
                return _board_status_id;
            }
            set
            {
                Onboard_status_idChanging(value);
                ReportPropertyChanging("board_status_id");
                _board_status_id = StructuralObject.SetValidValue(value, "board_status_id");
                ReportPropertyChanged("board_status_id");
                Onboard_status_idChanged();
            }
        }
        private global::System.Int16 _board_status_id;
        partial void Onboard_status_idChanging(global::System.Int16 value);
        partial void Onboard_status_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 module_id
        {
            get
            {
                return _module_id;
            }
            set
            {
                Onmodule_idChanging(value);
                ReportPropertyChanging("module_id");
                _module_id = StructuralObject.SetValidValue(value, "module_id");
                ReportPropertyChanged("module_id");
                Onmodule_idChanged();
            }
        }
        private global::System.Int16 _module_id;
        partial void Onmodule_idChanging(global::System.Int16 value);
        partial void Onmodule_idChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="cma_mls_modules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cma_mls_modules : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cma_mls_modules object.
        /// </summary>
        /// <param name="module_id">Initial value of the module_id property.</param>
        /// <param name="module_name">Initial value of the module_name property.</param>
        public static cma_mls_modules Createcma_mls_modules(global::System.Int16 module_id, global::System.String module_name)
        {
            cma_mls_modules cma_mls_modules = new cma_mls_modules();
            cma_mls_modules.module_id = module_id;
            cma_mls_modules.module_name = module_name;
            return cma_mls_modules;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 module_id
        {
            get
            {
                return _module_id;
            }
            set
            {
                if (_module_id != value)
                {
                    Onmodule_idChanging(value);
                    ReportPropertyChanging("module_id");
                    _module_id = StructuralObject.SetValidValue(value, "module_id");
                    ReportPropertyChanged("module_id");
                    Onmodule_idChanged();
                }
            }
        }
        private global::System.Int16 _module_id;
        partial void Onmodule_idChanging(global::System.Int16 value);
        partial void Onmodule_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String module_name
        {
            get
            {
                return _module_name;
            }
            set
            {
                Onmodule_nameChanging(value);
                ReportPropertyChanging("module_name");
                _module_name = StructuralObject.SetValidValue(value, false, "module_name");
                ReportPropertyChanged("module_name");
                Onmodule_nameChanged();
            }
        }
        private global::System.String _module_name;
        partial void Onmodule_nameChanging(global::System.String value);
        partial void Onmodule_nameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TCSModelProduction", "FK_tcs_indexed_datasources_cma_mls_modules", "tcs_indexed_datasources")]
        public tcs_indexed_datasources tcs_indexed_datasources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_indexed_datasources>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "tcs_indexed_datasources").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_indexed_datasources>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "tcs_indexed_datasources").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tcs_indexed_datasources> tcs_indexed_datasourcesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_indexed_datasources>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "tcs_indexed_datasources");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tcs_indexed_datasources>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "tcs_indexed_datasources", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="tcs_error_log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tcs_error_log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tcs_error_log object.
        /// </summary>
        /// <param name="request_id">Initial value of the request_id property.</param>
        /// <param name="error_code">Initial value of the error_code property.</param>
        /// <param name="error_type">Initial value of the error_type property.</param>
        /// <param name="error_msg">Initial value of the error_msg property.</param>
        public static tcs_error_log Createtcs_error_log(global::System.Int64 request_id, global::System.Int32 error_code, global::System.Int16 error_type, global::System.String error_msg)
        {
            tcs_error_log tcs_error_log = new tcs_error_log();
            tcs_error_log.request_id = request_id;
            tcs_error_log.error_code = error_code;
            tcs_error_log.error_type = error_type;
            tcs_error_log.error_msg = error_msg;
            return tcs_error_log;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 request_id
        {
            get
            {
                return _request_id;
            }
            set
            {
                if (_request_id != value)
                {
                    Onrequest_idChanging(value);
                    ReportPropertyChanging("request_id");
                    _request_id = StructuralObject.SetValidValue(value, "request_id");
                    ReportPropertyChanged("request_id");
                    Onrequest_idChanged();
                }
            }
        }
        private global::System.Int64 _request_id;
        partial void Onrequest_idChanging(global::System.Int64 value);
        partial void Onrequest_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 error_code
        {
            get
            {
                return _error_code;
            }
            set
            {
                Onerror_codeChanging(value);
                ReportPropertyChanging("error_code");
                _error_code = StructuralObject.SetValidValue(value, "error_code");
                ReportPropertyChanged("error_code");
                Onerror_codeChanged();
            }
        }
        private global::System.Int32 _error_code;
        partial void Onerror_codeChanging(global::System.Int32 value);
        partial void Onerror_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 error_type
        {
            get
            {
                return _error_type;
            }
            set
            {
                Onerror_typeChanging(value);
                ReportPropertyChanging("error_type");
                _error_type = StructuralObject.SetValidValue(value, "error_type");
                ReportPropertyChanged("error_type");
                Onerror_typeChanged();
            }
        }
        private global::System.Int16 _error_type;
        partial void Onerror_typeChanging(global::System.Int16 value);
        partial void Onerror_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String error_msg
        {
            get
            {
                return _error_msg;
            }
            set
            {
                Onerror_msgChanging(value);
                ReportPropertyChanging("error_msg");
                _error_msg = StructuralObject.SetValidValue(value, false, "error_msg");
                ReportPropertyChanged("error_msg");
                Onerror_msgChanged();
            }
        }
        private global::System.String _error_msg;
        partial void Onerror_msgChanging(global::System.String value);
        partial void Onerror_msgChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TCSModelProduction", "FK_LOG_HAS_ERROR", "tcs_request_log")]
        public tcs_request_log tcs_request_log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_request_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_request_log").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_request_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_request_log").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tcs_request_log> tcs_request_logReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_request_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_request_log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tcs_request_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_request_log", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="tcs_indexed_datasources")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tcs_indexed_datasources : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tcs_indexed_datasources object.
        /// </summary>
        /// <param name="module_id">Initial value of the module_id property.</param>
        public static tcs_indexed_datasources Createtcs_indexed_datasources(global::System.Int16 module_id)
        {
            tcs_indexed_datasources tcs_indexed_datasources = new tcs_indexed_datasources();
            tcs_indexed_datasources.module_id = module_id;
            return tcs_indexed_datasources;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 module_id
        {
            get
            {
                return _module_id;
            }
            set
            {
                if (_module_id != value)
                {
                    Onmodule_idChanging(value);
                    ReportPropertyChanging("module_id");
                    _module_id = StructuralObject.SetValidValue(value, "module_id");
                    ReportPropertyChanged("module_id");
                    Onmodule_idChanged();
                }
            }
        }
        private global::System.Int16 _module_id;
        partial void Onmodule_idChanging(global::System.Int16 value);
        partial void Onmodule_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> when_created
        {
            get
            {
                return _when_created;
            }
            set
            {
                Onwhen_createdChanging(value);
                ReportPropertyChanging("when_created");
                _when_created = StructuralObject.SetValidValue(value, "when_created");
                ReportPropertyChanged("when_created");
                Onwhen_createdChanged();
            }
        }
        private Nullable<global::System.DateTime> _when_created;
        partial void Onwhen_createdChanging(Nullable<global::System.DateTime> value);
        partial void Onwhen_createdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TCSModelProduction", "FK_tcs_indexed_datasources_cma_mls_modules", "cma_mls_modules")]
        public cma_mls_modules cma_mls_modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cma_mls_modules>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "cma_mls_modules").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cma_mls_modules>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "cma_mls_modules").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cma_mls_modules> cma_mls_modulesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cma_mls_modules>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "cma_mls_modules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cma_mls_modules>("TCSModelProduction.FK_tcs_indexed_datasources_cma_mls_modules", "cma_mls_modules", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="tcs_module_id_to_data_source_id")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tcs_module_id_to_data_source_id : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tcs_module_id_to_data_source_id object.
        /// </summary>
        /// <param name="module_id">Initial value of the module_id property.</param>
        /// <param name="data_source_id">Initial value of the data_source_id property.</param>
        public static tcs_module_id_to_data_source_id Createtcs_module_id_to_data_source_id(global::System.Int16 module_id, global::System.String data_source_id)
        {
            tcs_module_id_to_data_source_id tcs_module_id_to_data_source_id = new tcs_module_id_to_data_source_id();
            tcs_module_id_to_data_source_id.module_id = module_id;
            tcs_module_id_to_data_source_id.data_source_id = data_source_id;
            return tcs_module_id_to_data_source_id;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 module_id
        {
            get
            {
                return _module_id;
            }
            set
            {
                if (_module_id != value)
                {
                    Onmodule_idChanging(value);
                    ReportPropertyChanging("module_id");
                    _module_id = StructuralObject.SetValidValue(value, "module_id");
                    ReportPropertyChanged("module_id");
                    Onmodule_idChanged();
                }
            }
        }
        private global::System.Int16 _module_id;
        partial void Onmodule_idChanging(global::System.Int16 value);
        partial void Onmodule_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String data_source_id
        {
            get
            {
                return _data_source_id;
            }
            set
            {
                if (_data_source_id != value)
                {
                    Ondata_source_idChanging(value);
                    ReportPropertyChanging("data_source_id");
                    _data_source_id = StructuralObject.SetValidValue(value, false, "data_source_id");
                    ReportPropertyChanged("data_source_id");
                    Ondata_source_idChanged();
                }
            }
        }
        private global::System.String _data_source_id;
        partial void Ondata_source_idChanging(global::System.String value);
        partial void Ondata_source_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data_source_name
        {
            get
            {
                return _data_source_name;
            }
            set
            {
                Ondata_source_nameChanging(value);
                ReportPropertyChanging("data_source_name");
                _data_source_name = StructuralObject.SetValidValue(value, true, "data_source_name");
                ReportPropertyChanged("data_source_name");
                Ondata_source_nameChanged();
            }
        }
        private global::System.String _data_source_name;
        partial void Ondata_source_nameChanging(global::System.String value);
        partial void Ondata_source_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login_name
        {
            get
            {
                return _login_name;
            }
            set
            {
                Onlogin_nameChanging(value);
                ReportPropertyChanging("login_name");
                _login_name = StructuralObject.SetValidValue(value, true, "login_name");
                ReportPropertyChanged("login_name");
                Onlogin_nameChanged();
            }
        }
        private global::System.String _login_name;
        partial void Onlogin_nameChanging(global::System.String value);
        partial void Onlogin_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_agent
        {
            get
            {
                return _user_agent;
            }
            set
            {
                Onuser_agentChanging(value);
                ReportPropertyChanging("user_agent");
                _user_agent = StructuralObject.SetValidValue(value, true, "user_agent");
                ReportPropertyChanged("user_agent");
                Onuser_agentChanged();
            }
        }
        private global::System.String _user_agent;
        partial void Onuser_agentChanging(global::System.String value);
        partial void Onuser_agentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ua_password
        {
            get
            {
                return _ua_password;
            }
            set
            {
                Onua_passwordChanging(value);
                ReportPropertyChanging("ua_password");
                _ua_password = StructuralObject.SetValidValue(value, true, "ua_password");
                ReportPropertyChanged("ua_password");
                Onua_passwordChanged();
            }
        }
        private global::System.String _ua_password;
        partial void Onua_passwordChanging(global::System.String value);
        partial void Onua_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_open_house_only
        {
            get
            {
                return _is_open_house_only;
            }
            set
            {
                Onis_open_house_onlyChanging(value);
                ReportPropertyChanging("is_open_house_only");
                _is_open_house_only = StructuralObject.SetValidValue(value, "is_open_house_only");
                ReportPropertyChanged("is_open_house_only");
                Onis_open_house_onlyChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_open_house_only;
        partial void Onis_open_house_onlyChanging(Nullable<global::System.Boolean> value);
        partial void Onis_open_house_onlyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String residential_class
        {
            get
            {
                return _residential_class;
            }
            set
            {
                Onresidential_classChanging(value);
                ReportPropertyChanging("residential_class");
                _residential_class = StructuralObject.SetValidValue(value, true, "residential_class");
                ReportPropertyChanged("residential_class");
                Onresidential_classChanged();
            }
        }
        private global::System.String _residential_class;
        partial void Onresidential_classChanging(global::System.String value);
        partial void Onresidential_classChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> data_source_type
        {
            get
            {
                return _data_source_type;
            }
            set
            {
                Ondata_source_typeChanging(value);
                ReportPropertyChanging("data_source_type");
                _data_source_type = StructuralObject.SetValidValue(value, "data_source_type");
                ReportPropertyChanged("data_source_type");
                Ondata_source_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _data_source_type;
        partial void Ondata_source_typeChanging(Nullable<global::System.Int32> value);
        partial void Ondata_source_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_modified
        {
            get
            {
                return _last_modified;
            }
            set
            {
                Onlast_modifiedChanging(value);
                ReportPropertyChanging("last_modified");
                _last_modified = StructuralObject.SetValidValue(value, "last_modified");
                ReportPropertyChanged("last_modified");
                Onlast_modifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_modified;
        partial void Onlast_modifiedChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_modifiedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCSModelProduction", Name="tcs_request_log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tcs_request_log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tcs_request_log object.
        /// </summary>
        /// <param name="when_created">Initial value of the when_created property.</param>
        /// <param name="request_id">Initial value of the request_id property.</param>
        /// <param name="board_id">Initial value of the board_id property.</param>
        /// <param name="request_xml">Initial value of the request_xml property.</param>
        /// <param name="function_id">Initial value of the function_id property.</param>
        /// <param name="location_path">Initial value of the location_path property.</param>
        /// <param name="web_server">Initial value of the web_server property.</param>
        /// <param name="mls_user_name">Initial value of the mls_user_name property.</param>
        /// <param name="zip">Initial value of the zip property.</param>
        /// <param name="client_name">Initial value of the client_name property.</param>
        /// <param name="client_task_ref">Initial value of the client_task_ref property.</param>
        public static tcs_request_log Createtcs_request_log(global::System.DateTime when_created, global::System.Int64 request_id, global::System.Int16 board_id, global::System.String request_xml, global::System.Int16 function_id, global::System.String location_path, global::System.String web_server, global::System.String mls_user_name, global::System.String zip, global::System.String client_name, global::System.String client_task_ref)
        {
            tcs_request_log tcs_request_log = new tcs_request_log();
            tcs_request_log.when_created = when_created;
            tcs_request_log.request_id = request_id;
            tcs_request_log.board_id = board_id;
            tcs_request_log.request_xml = request_xml;
            tcs_request_log.function_id = function_id;
            tcs_request_log.location_path = location_path;
            tcs_request_log.web_server = web_server;
            tcs_request_log.mls_user_name = mls_user_name;
            tcs_request_log.zip = zip;
            tcs_request_log.client_name = client_name;
            tcs_request_log.client_task_ref = client_task_ref;
            return tcs_request_log;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime when_created
        {
            get
            {
                return _when_created;
            }
            set
            {
                Onwhen_createdChanging(value);
                ReportPropertyChanging("when_created");
                _when_created = StructuralObject.SetValidValue(value, "when_created");
                ReportPropertyChanged("when_created");
                Onwhen_createdChanged();
            }
        }
        private global::System.DateTime _when_created;
        partial void Onwhen_createdChanging(global::System.DateTime value);
        partial void Onwhen_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 request_id
        {
            get
            {
                return _request_id;
            }
            set
            {
                if (_request_id != value)
                {
                    Onrequest_idChanging(value);
                    ReportPropertyChanging("request_id");
                    _request_id = StructuralObject.SetValidValue(value, "request_id");
                    ReportPropertyChanged("request_id");
                    Onrequest_idChanged();
                }
            }
        }
        private global::System.Int64 _request_id;
        partial void Onrequest_idChanging(global::System.Int64 value);
        partial void Onrequest_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 board_id
        {
            get
            {
                return _board_id;
            }
            set
            {
                Onboard_idChanging(value);
                ReportPropertyChanging("board_id");
                _board_id = StructuralObject.SetValidValue(value, "board_id");
                ReportPropertyChanged("board_id");
                Onboard_idChanged();
            }
        }
        private global::System.Int16 _board_id;
        partial void Onboard_idChanging(global::System.Int16 value);
        partial void Onboard_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String request_xml
        {
            get
            {
                return _request_xml;
            }
            set
            {
                Onrequest_xmlChanging(value);
                ReportPropertyChanging("request_xml");
                _request_xml = StructuralObject.SetValidValue(value, false, "request_xml");
                ReportPropertyChanged("request_xml");
                Onrequest_xmlChanged();
            }
        }
        private global::System.String _request_xml;
        partial void Onrequest_xmlChanging(global::System.String value);
        partial void Onrequest_xmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 function_id
        {
            get
            {
                return _function_id;
            }
            set
            {
                Onfunction_idChanging(value);
                ReportPropertyChanging("function_id");
                _function_id = StructuralObject.SetValidValue(value, "function_id");
                ReportPropertyChanged("function_id");
                Onfunction_idChanged();
            }
        }
        private global::System.Int16 _function_id;
        partial void Onfunction_idChanging(global::System.Int16 value);
        partial void Onfunction_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location_path
        {
            get
            {
                return _location_path;
            }
            set
            {
                Onlocation_pathChanging(value);
                ReportPropertyChanging("location_path");
                _location_path = StructuralObject.SetValidValue(value, false, "location_path");
                ReportPropertyChanged("location_path");
                Onlocation_pathChanged();
            }
        }
        private global::System.String _location_path;
        partial void Onlocation_pathChanging(global::System.String value);
        partial void Onlocation_pathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String web_server
        {
            get
            {
                return _web_server;
            }
            set
            {
                Onweb_serverChanging(value);
                ReportPropertyChanging("web_server");
                _web_server = StructuralObject.SetValidValue(value, false, "web_server");
                ReportPropertyChanged("web_server");
                Onweb_serverChanged();
            }
        }
        private global::System.String _web_server;
        partial void Onweb_serverChanging(global::System.String value);
        partial void Onweb_serverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mls_user_name
        {
            get
            {
                return _mls_user_name;
            }
            set
            {
                Onmls_user_nameChanging(value);
                ReportPropertyChanging("mls_user_name");
                _mls_user_name = StructuralObject.SetValidValue(value, false, "mls_user_name");
                ReportPropertyChanged("mls_user_name");
                Onmls_user_nameChanged();
            }
        }
        private global::System.String _mls_user_name;
        partial void Onmls_user_nameChanging(global::System.String value);
        partial void Onmls_user_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, false, "zip");
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String client_name
        {
            get
            {
                return _client_name;
            }
            set
            {
                Onclient_nameChanging(value);
                ReportPropertyChanging("client_name");
                _client_name = StructuralObject.SetValidValue(value, false, "client_name");
                ReportPropertyChanged("client_name");
                Onclient_nameChanged();
            }
        }
        private global::System.String _client_name;
        partial void Onclient_nameChanging(global::System.String value);
        partial void Onclient_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String client_task_ref
        {
            get
            {
                return _client_task_ref;
            }
            set
            {
                Onclient_task_refChanging(value);
                ReportPropertyChanging("client_task_ref");
                _client_task_ref = StructuralObject.SetValidValue(value, false, "client_task_ref");
                ReportPropertyChanged("client_task_ref");
                Onclient_task_refChanged();
            }
        }
        private global::System.String _client_task_ref;
        partial void Onclient_task_refChanging(global::System.String value);
        partial void Onclient_task_refChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TCSModelProduction", "FK_LOG_HAS_ERROR", "tcs_error_log")]
        public tcs_error_log tcs_error_log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_error_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_error_log").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_error_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_error_log").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tcs_error_log> tcs_error_logReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tcs_error_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_error_log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tcs_error_log>("TCSModelProduction.FK_LOG_HAS_ERROR", "tcs_error_log", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TCSModelProduction", Name="tcs_GetBoardID_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class tcs_GetBoardID_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tcs_GetBoardID_Result object.
        /// </summary>
        /// <param name="board_id">Initial value of the board_id property.</param>
        public static tcs_GetBoardID_Result Createtcs_GetBoardID_Result(global::System.Int16 board_id)
        {
            tcs_GetBoardID_Result tcs_GetBoardID_Result = new tcs_GetBoardID_Result();
            tcs_GetBoardID_Result.board_id = board_id;
            return tcs_GetBoardID_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 board_id
        {
            get
            {
                return _board_id;
            }
            set
            {
                Onboard_idChanging(value);
                ReportPropertyChanging("board_id");
                _board_id = StructuralObject.SetValidValue(value, "board_id");
                ReportPropertyChanged("board_id");
                Onboard_idChanged();
            }
        }
        private global::System.Int16 _board_id;
        partial void Onboard_idChanging(global::System.Int16 value);
        partial void Onboard_idChanged();

        #endregion

    }

    #endregion

}
